### PR TITLE
Support 1903

### PR DESCRIPTION
**Pull request by thxCode**
**Issue:**
https://github.com/rancher/rancher/issues/16460

### CODE REVIEW

**Comment by loganhz** [comment]
Please update manifest.tmpl file for 1903

**Comment by thxCode** [comment]
Updated

**Comment by loganhz** [comment]
lgtm

**Comment by cjellick** [comment]
@cloudnautique or @drpebcak can you review?

**Review by drpebcak — APPROVED** [review]

**Pull request merged**
